// ##############################################################

// DO NOT EDIT -- TEMPORARY C File generated by parse_robdecls.py

// ##############################################################

// WARNING IGNORED variable name *dienc
// WARNING IGNORED variable name *dout_buf
// WARNING IGNORED variable name *adc
// WARNING IGNORED variable name *dac
// WARNING IGNORED variable name *adcvolts
// WARNING IGNORED variable name *dacvolts
// WARNING IGNORED variable name *adcvoltsmean
// WARNING IGNORED variable name *adcvoltsmed
// WARNING IGNORED variable name *adcvoltsprev
// WARNING IGNORED variable name *adcvoltsfilt
// WARNING IGNORED variable name *adcvoltspfilt
// WARNING IGNORED variable name (*slot_fns[32])(u32)
// WARNING IGNORED variable name (*log_fns[32])(void)
// WARNING IGNORED variable name (*ref_fns[32])(void)
// WARNING IGNORED variable name *ci_fifo_buffer
// WARNING IGNORED variable name (*read_sensors) (void)
// WARNING IGNORED variable name (*read_reference) (void)
// WARNING IGNORED variable name (*compute_controls) (void)
// WARNING IGNORED variable name (*check_safety) (void)
// WARNING IGNORED variable name (*write_actuators) (void)
// WARNING IGNORED variable name (*write_display) (void)

#include <stdlib.h>
#include <signal.h>
#include "ruser.h"
#include "rtl_inc.h"
#include "robdecls.h"


Ob *ob;

Robot *robot;

Daq *daq;

Game *game;

Moh *moh;

Dyncmp_var *dyncmp_var;



s32 main(void) {

	// IGNORED Slot,slot because it is an array of a non-atomic type (for type Ob)
	printf("Ob s8 tag 8 %u\n", (unsigned int)&ob->tag ); // atomic
	printf("Ob RT_TASK main_thread 0 %u\n", (unsigned int)&ob->main_thread ); // atomic
	printf("Ob u32 doinit 0 %u\n", (unsigned int)&ob->doinit ); // atomic
	printf("Ob u32 didinit 0 %u\n", (unsigned int)&ob->didinit ); // atomic
	printf("Ob u32 quit 0 %u\n", (unsigned int)&ob->quit ); // atomic
	printf("Ob u32 i 0 %u\n", (unsigned int)&ob->i ); // atomic
	printf("Ob u32 fasti 0 %u\n", (unsigned int)&ob->fasti ); // atomic
	printf("Ob u32 samplenum 0 %u\n", (unsigned int)&ob->samplenum ); // atomic
	printf("Ob u32 total_samples 0 %u\n", (unsigned int)&ob->total_samples ); // atomic
	printf("Ob u32 Hz 0 %u\n", (unsigned int)&ob->Hz ); // atomic
	printf("Ob f64 rate 0 %u\n", (unsigned int)&ob->rate ); // atomic
	printf("Ob u32 irate 0 %u\n", (unsigned int)&ob->irate ); // atomic
	printf("Ob u32 ovsample 0 %u\n", (unsigned int)&ob->ovsample ); // atomic
	printf("Ob u32 fastHz 0 %u\n", (unsigned int)&ob->fastHz ); // atomic
	printf("Ob f64 fastrate 0 %u\n", (unsigned int)&ob->fastrate ); // atomic
	printf("Ob u32 fastirate 0 %u\n", (unsigned int)&ob->fastirate ); // atomic
	printf("Ob u32 ticks30Hz 0 %u\n", (unsigned int)&ob->ticks30Hz ); // atomic
	printf("Ob f64 stiff 0 %u\n", (unsigned int)&ob->stiff ); // atomic
	printf("Ob f64 damp 0 %u\n", (unsigned int)&ob->damp ); // atomic
	printf("Ob f64 curl 0 %u\n", (unsigned int)&ob->curl ); // atomic
	printf("Ob f64 const_force_x 0 %u\n", (unsigned int)&ob->const_force.x ); // atomic
	printf("Ob f64 const_force_y 0 %u\n", (unsigned int)&ob->const_force.y ); // atomic
	printf("Ob f64 side_stiff 0 %u\n", (unsigned int)&ob->side_stiff ); // atomic
	printf("Ob f64 pfomax 0 %u\n", (unsigned int)&ob->pfomax ); // atomic
	printf("Ob f64 pfotest 0 %u\n", (unsigned int)&ob->pfotest ); // atomic
	printf("Ob u32 busy 0 %u\n", (unsigned int)&ob->busy ); // atomic
	printf("Ob u32 paused 0 %u\n", (unsigned int)&ob->paused ); // atomic
	printf("Ob u32 fault 0 %u\n", (unsigned int)&ob->fault ); // atomic
	printf("Ob s32 stiffener 0 %u\n", (unsigned int)&ob->stiffener ); // atomic
	printf("Ob s32 stiff_delta 0 %u\n", (unsigned int)&ob->stiff_delta ); // atomic
	printf("Ob u32 no_motors 0 %u\n", (unsigned int)&ob->no_motors ); // atomic
	printf("Ob u32 restart_go 0 %u\n", (unsigned int)&ob->restart.go ); // atomic
	printf("Ob u32 restart_Hz 0 %u\n", (unsigned int)&ob->restart.Hz ); // atomic
	printf("Ob u32 restart_ovsample 0 %u\n", (unsigned int)&ob->restart.ovsample ); // atomic
	printf("Ob f64 restart_stiff 0 %u\n", (unsigned int)&ob->restart.stiff ); // atomic
	printf("Ob f64 restart_damp 0 %u\n", (unsigned int)&ob->restart.damp ); // atomic
	printf("Ob SRTIME times_time_at_start 0 %u\n", (unsigned int)&ob->times.time_at_start ); // atomic
	printf("Ob SRTIME times_time_before_sample 0 %u\n", (unsigned int)&ob->times.time_before_sample ); // atomic
	printf("Ob SRTIME times_time_after_sample 0 %u\n", (unsigned int)&ob->times.time_after_sample ); // atomic
	printf("Ob SRTIME times_time_before_last_sample 0 %u\n", (unsigned int)&ob->times.time_before_last_sample ); // atomic
	printf("Ob SRTIME times_time_after_last_sample 0 %u\n", (unsigned int)&ob->times.time_after_last_sample ); // atomic
	printf("Ob SRTIME times_time_delta_sample 0 %u\n", (unsigned int)&ob->times.time_delta_sample ); // atomic
	printf("Ob SRTIME times_time_delta_tick 0 %u\n", (unsigned int)&ob->times.time_delta_tick ); // atomic
	printf("Ob SRTIME times_time_delta_call 0 %u\n", (unsigned int)&ob->times.time_delta_call ); // atomic
	printf("Ob SRTIME times_time_since_start 0 %u\n", (unsigned int)&ob->times.time_since_start ); // atomic
	printf("Ob u32 times_ns_delta_call 0 %u\n", (unsigned int)&ob->times.ns_delta_call ); // atomic
	printf("Ob u32 times_ns_delta_tick 0 %u\n", (unsigned int)&ob->times.ns_delta_tick ); // atomic
	printf("Ob u32 times_ns_delta_tick_thresh 0 %u\n", (unsigned int)&ob->times.ns_delta_tick_thresh ); // atomic
	printf("Ob u32 times_ns_delta_sample 0 %u\n", (unsigned int)&ob->times.ns_delta_sample ); // atomic
	printf("Ob u32 times_ns_delta_sample_thresh 0 %u\n", (unsigned int)&ob->times.ns_delta_sample_thresh ); // atomic
	printf("Ob u32 times_ms_since_start 0 %u\n", (unsigned int)&ob->times.ms_since_start ); // atomic
	printf("Ob u32 times_sec 0 %u\n", (unsigned int)&ob->times.sec ); // atomic
	printf("Ob u32 times_ns_max_delta_tick 0 %u\n", (unsigned int)&ob->times.ns_max_delta_tick ); // atomic
	printf("Ob u32 times_ns_max_delta_sample 0 %u\n", (unsigned int)&ob->times.ns_max_delta_sample ); // atomic
	printf("Ob u32 have_tach 0 %u\n", (unsigned int)&ob->have_tach ); // atomic
	printf("Ob u32 have_ft 0 %u\n", (unsigned int)&ob->have_ft ); // atomic
	printf("Ob u32 have_isaft 0 %u\n", (unsigned int)&ob->have_isaft ); // atomic
	printf("Ob u32 have_accel 0 %u\n", (unsigned int)&ob->have_accel ); // atomic
	printf("Ob u32 have_grasp 0 %u\n", (unsigned int)&ob->have_grasp ); // atomic
	printf("Ob u32 have_planar 0 %u\n", (unsigned int)&ob->have_planar ); // atomic
	printf("Ob u32 have_wrist 0 %u\n", (unsigned int)&ob->have_wrist ); // atomic
	printf("Ob u32 have_ankle 0 %u\n", (unsigned int)&ob->have_ankle ); // atomic
	printf("Ob u32 have_linear 0 %u\n", (unsigned int)&ob->have_linear ); // atomic
	printf("Ob u32 have_hand 0 %u\n", (unsigned int)&ob->have_hand ); // atomic
	printf("Ob u32 have_planar_incenc 0 %u\n", (unsigned int)&ob->have_planar_incenc ); // atomic
	printf("Ob u32 have_planar_ao8 0 %u\n", (unsigned int)&ob->have_planar_ao8 ); // atomic
	printf("Ob u32 copy_slot_id 0 %u\n", (unsigned int)&ob->copy_slot.id ); // atomic
	printf("Ob u32 copy_slot_i 0 %u\n", (unsigned int)&ob->copy_slot.i ); // atomic
	printf("Ob u32 copy_slot_incr 0 %u\n", (unsigned int)&ob->copy_slot.incr ); // atomic
	printf("Ob u32 copy_slot_term 0 %u\n", (unsigned int)&ob->copy_slot.term ); // atomic
	printf("Ob u32 copy_slot_termi 0 %u\n", (unsigned int)&ob->copy_slot.termi ); // atomic
	printf("Ob f64 copy_slot_b0_point_x 0 %u\n", (unsigned int)&ob->copy_slot.b0.point.x ); // atomic
	printf("Ob f64 copy_slot_b0_point_y 0 %u\n", (unsigned int)&ob->copy_slot.b0.point.y ); // atomic
	printf("Ob f64 copy_slot_b0_w 0 %u\n", (unsigned int)&ob->copy_slot.b0.w ); // atomic
	printf("Ob f64 copy_slot_b0_h 0 %u\n", (unsigned int)&ob->copy_slot.b0.h ); // atomic
	printf("Ob f64 copy_slot_b1_point_x 0 %u\n", (unsigned int)&ob->copy_slot.b1.point.x ); // atomic
	printf("Ob f64 copy_slot_b1_point_y 0 %u\n", (unsigned int)&ob->copy_slot.b1.point.y ); // atomic
	printf("Ob f64 copy_slot_b1_w 0 %u\n", (unsigned int)&ob->copy_slot.b1.w ); // atomic
	printf("Ob f64 copy_slot_b1_h 0 %u\n", (unsigned int)&ob->copy_slot.b1.h ); // atomic
	printf("Ob f64 copy_slot_bcur_point_x 0 %u\n", (unsigned int)&ob->copy_slot.bcur.point.x ); // atomic
	printf("Ob f64 copy_slot_bcur_point_y 0 %u\n", (unsigned int)&ob->copy_slot.bcur.point.y ); // atomic
	printf("Ob f64 copy_slot_bcur_w 0 %u\n", (unsigned int)&ob->copy_slot.bcur.w ); // atomic
	printf("Ob f64 copy_slot_bcur_h 0 %u\n", (unsigned int)&ob->copy_slot.bcur.h ); // atomic
	printf("Ob f64 copy_slot_rot 0 %u\n", (unsigned int)&ob->copy_slot.rot ); // atomic
	printf("Ob u32 copy_slot_fnid 0 %u\n", (unsigned int)&ob->copy_slot.fnid ); // atomic
	printf("Ob u32 copy_slot_running 0 %u\n", (unsigned int)&ob->copy_slot.running ); // atomic
	printf("Ob u32 copy_slot_go 0 %u\n", (unsigned int)&ob->copy_slot.go ); // atomic
	printf("Ob f64 pm_active_power 0 %u\n", (unsigned int)&ob->pm.active_power ); // atomic
	printf("Ob f64 pm_min_jerk_deviation 0 %u\n", (unsigned int)&ob->pm.min_jerk_deviation ); // atomic
	printf("Ob f64 pm_min_jerk_dgraph 0 %u\n", (unsigned int)&ob->pm.min_jerk_dgraph ); // atomic
	printf("Ob f64 pm_dist_straight_line 0 %u\n", (unsigned int)&ob->pm.dist_straight_line ); // atomic
	printf("Ob f64 pm_max_dist_along_axis 0 %u\n", (unsigned int)&ob->pm.max_dist_along_axis ); // atomic
	printf("Ob u32 pm_npoints 0 %u\n", (unsigned int)&ob->pm.npoints ); // atomic
	printf("Ob u32 pm_five_d 0 %u\n", (unsigned int)&ob->pm.five_d ); // atomic
	printf("Ob u32 slot_max 0 %u\n", (unsigned int)&ob->slot_max ); // atomic
	printf("Ob f64 pi 0 %u\n", (unsigned int)&ob->pi ); // atomic
	printf("Ob u32 nlog 0 %u\n", (unsigned int)&ob->nlog ); // atomic
	printf("Ob f64 log 32 %u\n", (unsigned int)&ob->log ); // atomic
	printf("Ob u32 logfnid 0 %u\n", (unsigned int)&ob->logfnid ); // atomic
	printf("Ob u32 ndisp 0 %u\n", (unsigned int)&ob->ndisp ); // atomic
	printf("Ob f64 disp 32 %u\n", (unsigned int)&ob->disp ); // atomic
	printf("Ob u32 nref 0 %u\n", (unsigned int)&ob->nref ); // atomic
	printf("Ob f64 refin 32 %u\n", (unsigned int)&ob->refin ); // atomic
	printf("Ob u32 reffnid 0 %u\n", (unsigned int)&ob->reffnid ); // atomic
	printf("Ob RT_PIPE dififo 0 %u\n", (unsigned int)&ob->dififo ); // atomic
	printf("Ob RT_PIPE dofifo 0 %u\n", (unsigned int)&ob->dofifo ); // atomic
	printf("Ob RT_PIPE eofifo 0 %u\n", (unsigned int)&ob->eofifo ); // atomic
	printf("Ob RT_PIPE cififo 0 %u\n", (unsigned int)&ob->cififo ); // atomic
	printf("Ob RT_PIPE ddfifo 0 %u\n", (unsigned int)&ob->ddfifo ); // atomic
	printf("Ob RT_PIPE tcfifo 0 %u\n", (unsigned int)&ob->tcfifo ); // atomic
	printf("Ob u32 ntickfifo 0 %u\n", (unsigned int)&ob->ntickfifo ); // atomic
	printf("Ob u32 fifolen 0 %u\n", (unsigned int)&ob->fifolen ); // atomic
	printf("Ob f64 safety_pos 0 %u\n", (unsigned int)&ob->safety.pos ); // atomic
	printf("Ob f64 safety_minx 0 %u\n", (unsigned int)&ob->safety.minx ); // atomic
	printf("Ob f64 safety_maxx 0 %u\n", (unsigned int)&ob->safety.maxx ); // atomic
	printf("Ob f64 safety_miny 0 %u\n", (unsigned int)&ob->safety.miny ); // atomic
	printf("Ob f64 safety_maxy 0 %u\n", (unsigned int)&ob->safety.maxy ); // atomic
	printf("Ob f64 safety_vel 0 %u\n", (unsigned int)&ob->safety.vel ); // atomic
	printf("Ob f64 safety_torque 0 %u\n", (unsigned int)&ob->safety.torque ); // atomic
	printf("Ob f64 safety_ramp 0 %u\n", (unsigned int)&ob->safety.ramp ); // atomic
	printf("Ob f64 safety_damping_nms 0 %u\n", (unsigned int)&ob->safety.damping_nms ); // atomic
	printf("Ob f64 safety_velmag_kick 0 %u\n", (unsigned int)&ob->safety.velmag_kick ); // atomic
	printf("Ob u32 safety_override 0 %u\n", (unsigned int)&ob->safety.override ); // atomic
	printf("Ob f64 safety_motor_force_x 0 %u\n", (unsigned int)&ob->safety.motor_force.x ); // atomic
	printf("Ob f64 safety_motor_force_y 0 %u\n", (unsigned int)&ob->safety.motor_force.y ); // atomic
	printf("Ob u32 safety_planar_just_crossed_back 0 %u\n", (unsigned int)&ob->safety.planar_just_crossed_back ); // atomic
	printf("Ob u32 safety_was_planar_damping 0 %u\n", (unsigned int)&ob->safety.was_planar_damping ); // atomic
	printf("Ob u32 safety_active 0 %u\n", (unsigned int)&ob->safety.active ); // atomic
	printf("Ob u32 safety_has_applied 0 %u\n", (unsigned int)&ob->safety.has_applied ); // atomic
	printf("Ob u32 safety_damp_ret_ticks 0 %u\n", (unsigned int)&ob->safety.damp_ret_ticks ); // atomic
	printf("Ob f64 safety_damp_ret_secs 0 %u\n", (unsigned int)&ob->safety.damp_ret_secs ); // atomic
	printf("Ob u32 vibrate 0 %u\n", (unsigned int)&ob->vibrate ); // atomic
	printf("Ob s32 xvibe 0 %u\n", (unsigned int)&ob->xvibe ); // atomic
	printf("Ob s32 yvibe 0 %u\n", (unsigned int)&ob->yvibe ); // atomic
	printf("Ob f64 pos_x 0 %u\n", (unsigned int)&ob->pos.x ); // atomic
	printf("Ob f64 pos_y 0 %u\n", (unsigned int)&ob->pos.y ); // atomic
	printf("Ob f64 tach_vel_x 0 %u\n", (unsigned int)&ob->tach_vel.x ); // atomic
	printf("Ob f64 tach_vel_y 0 %u\n", (unsigned int)&ob->tach_vel.y ); // atomic
	printf("Ob f64 ftach_vel_x 0 %u\n", (unsigned int)&ob->ftach_vel.x ); // atomic
	printf("Ob f64 ftach_vel_y 0 %u\n", (unsigned int)&ob->ftach_vel.y ); // atomic
	printf("Ob f64 soft_vel_x 0 %u\n", (unsigned int)&ob->soft_vel.x ); // atomic
	printf("Ob f64 soft_vel_y 0 %u\n", (unsigned int)&ob->soft_vel.y ); // atomic
	printf("Ob f64 fsoft_vel_x 0 %u\n", (unsigned int)&ob->fsoft_vel.x ); // atomic
	printf("Ob f64 fsoft_vel_y 0 %u\n", (unsigned int)&ob->fsoft_vel.y ); // atomic
	printf("Ob f64 vel_x 0 %u\n", (unsigned int)&ob->vel.x ); // atomic
	printf("Ob f64 vel_y 0 %u\n", (unsigned int)&ob->vel.y ); // atomic
	printf("Ob f64 motor_force_x 0 %u\n", (unsigned int)&ob->motor_force.x ); // atomic
	printf("Ob f64 motor_force_y 0 %u\n", (unsigned int)&ob->motor_force.y ); // atomic
	printf("Ob f64 motor_torque_s 0 %u\n", (unsigned int)&ob->motor_torque.s ); // atomic
	printf("Ob f64 motor_torque_e 0 %u\n", (unsigned int)&ob->motor_torque.e ); // atomic
	printf("Ob f64 motor_volts_s 0 %u\n", (unsigned int)&ob->motor_volts.s ); // atomic
	printf("Ob f64 motor_volts_e 0 %u\n", (unsigned int)&ob->motor_volts.e ); // atomic
	printf("Ob f64 back_x 0 %u\n", (unsigned int)&ob->back.x ); // atomic
	printf("Ob f64 back_y 0 %u\n", (unsigned int)&ob->back.y ); // atomic
	printf("Ob f64 norm_x 0 %u\n", (unsigned int)&ob->norm.x ); // atomic
	printf("Ob f64 norm_y 0 %u\n", (unsigned int)&ob->norm.y ); // atomic
	printf("Ob f64 velmag 0 %u\n", (unsigned int)&ob->velmag ); // atomic
	printf("Ob f64 soft_accel_x 0 %u\n", (unsigned int)&ob->soft_accel.x ); // atomic
	printf("Ob f64 soft_accel_y 0 %u\n", (unsigned int)&ob->soft_accel.y ); // atomic
	printf("Ob f64 soft_accelmag 0 %u\n", (unsigned int)&ob->soft_accelmag ); // atomic
	printf("Ob f64 ref_pos_x 0 %u\n", (unsigned int)&ob->ref.pos.x ); // atomic
	printf("Ob f64 ref_pos_y 0 %u\n", (unsigned int)&ob->ref.pos.y ); // atomic
	printf("Ob f64 ref_vel_x 0 %u\n", (unsigned int)&ob->ref.vel.x ); // atomic
	printf("Ob f64 ref_vel_y 0 %u\n", (unsigned int)&ob->ref.vel.y ); // atomic
	printf("Ob f64 theta_s 0 %u\n", (unsigned int)&ob->theta.s ); // atomic
	printf("Ob f64 theta_e 0 %u\n", (unsigned int)&ob->theta.e ); // atomic
	printf("Ob f64 thetadot_s 0 %u\n", (unsigned int)&ob->thetadot.s ); // atomic
	printf("Ob f64 thetadot_e 0 %u\n", (unsigned int)&ob->thetadot.e ); // atomic
	printf("Ob f64 fthetadot_s 0 %u\n", (unsigned int)&ob->fthetadot.s ); // atomic
	printf("Ob f64 fthetadot_e 0 %u\n", (unsigned int)&ob->fthetadot.e ); // atomic
	printf("Ob f64 linear_pos 0 %u\n", (unsigned int)&ob->linear.pos ); // atomic
	printf("Ob f64 linear_vel 0 %u\n", (unsigned int)&ob->linear.vel ); // atomic
	printf("Ob f64 linear_fvel 0 %u\n", (unsigned int)&ob->linear.fvel ); // atomic
	printf("Ob f64 linear_force 0 %u\n", (unsigned int)&ob->linear.force ); // atomic
	printf("Ob f64 linear_back 0 %u\n", (unsigned int)&ob->linear.back ); // atomic
	printf("Ob f64 linear_norm 0 %u\n", (unsigned int)&ob->linear.norm ); // atomic
	printf("Ob f64 linear_offset 0 %u\n", (unsigned int)&ob->linear.offset ); // atomic
	printf("Ob f64 linear_ref_pos 0 %u\n", (unsigned int)&ob->linear.ref_pos ); // atomic
	printf("Ob f64 linear_stiff 0 %u\n", (unsigned int)&ob->linear.stiff ); // atomic
	printf("Ob f64 linear_damp 0 %u\n", (unsigned int)&ob->linear.damp ); // atomic
	printf("Ob f64 linear_force_bias 0 %u\n", (unsigned int)&ob->linear.force_bias ); // atomic
	printf("Ob f64 linear_pfomax 0 %u\n", (unsigned int)&ob->linear.pfomax ); // atomic
	printf("Ob f64 linear_pfotest 0 %u\n", (unsigned int)&ob->linear.pfotest ); // atomic
	printf("Ob u32 linear_adap_going_up 0 %u\n", (unsigned int)&ob->linear.adap_going_up ); // atomic
	printf("Ob u32 test_raw_torque 0 %u\n", (unsigned int)&ob->test_raw_torque ); // atomic
	printf("Ob f64 raw_torque_volts_s 0 %u\n", (unsigned int)&ob->raw_torque_volts.s ); // atomic
	printf("Ob f64 raw_torque_volts_e 0 %u\n", (unsigned int)&ob->raw_torque_volts.e ); // atomic
	printf("Ob f64 sin_period 0 %u\n", (unsigned int)&ob->sin_period ); // atomic
	printf("Ob f64 sin_amplitude 0 %u\n", (unsigned int)&ob->sin_amplitude ); // atomic
	printf("Ob u32 sin_which_motor 0 %u\n", (unsigned int)&ob->sin_which_motor ); // atomic
	printf("Ob u32 butcutoff 0 %u\n", (unsigned int)&ob->butcutoff ); // atomic
	printf("Ob f64 max_vel_x 0 %u\n", (unsigned int)&ob->max.vel.x ); // atomic
	printf("Ob f64 max_vel_y 0 %u\n", (unsigned int)&ob->max.vel.y ); // atomic
	printf("Ob f64 max_motor_force_x 0 %u\n", (unsigned int)&ob->max.motor_force.x ); // atomic
	printf("Ob f64 max_motor_force_y 0 %u\n", (unsigned int)&ob->max.motor_force.y ); // atomic
	printf("Ob f64 max_motor_torque_s 0 %u\n", (unsigned int)&ob->max.motor_torque.s ); // atomic
	printf("Ob f64 max_motor_torque_e 0 %u\n", (unsigned int)&ob->max.motor_torque.e ); // atomic
	printf("Ob u32 errnum 0 %u\n", (unsigned int)&ob->errnum ); // atomic
	printf("Ob u32 nerrors 0 %u\n", (unsigned int)&ob->nerrors ); // atomic
	printf("Ob u32 errori 128 %u\n", (unsigned int)&ob->errori ); // atomic
	printf("Ob u32 errorcode 128 %u\n", (unsigned int)&ob->errorcode ); // atomic
	printf("Ob u32 errorindex 0 %u\n", (unsigned int)&ob->errorindex ); // atomic
	printf("Ob f64 scr 64 %u\n", (unsigned int)&ob->scr ); // atomic
	printf("Ob f64 game 64 %u\n", (unsigned int)&ob->game ); // atomic
	printf("Ob f64 plg_debug 0 %u\n", (unsigned int)&ob->plg_debug ); // atomic
	printf("Ob f64 plg_ftzero 6 %u\n", (unsigned int)&ob->plg_ftzero ); // atomic
	printf("Ob u32 plg_ftzerocount 0 %u\n", (unsigned int)&ob->plg_ftzerocount ); // atomic
	printf("Ob f64 plg_curlmat 4 %u\n", (unsigned int)&ob->plg_curlmat ); // atomic
	printf("Ob f64 plg_stiffness 0 %u\n", (unsigned int)&ob->plg_stiffness ); // atomic
	printf("Ob f64 plg_damping 0 %u\n", (unsigned int)&ob->plg_damping ); // atomic
	printf("Ob f64 plg_p1x 0 %u\n", (unsigned int)&ob->plg_p1x ); // atomic
	printf("Ob f64 plg_p1y 0 %u\n", (unsigned int)&ob->plg_p1y ); // atomic
	printf("Ob f64 plg_p2x 0 %u\n", (unsigned int)&ob->plg_p2x ); // atomic
	printf("Ob f64 plg_p2y 0 %u\n", (unsigned int)&ob->plg_p2y ); // atomic
	printf("Ob f64 plg_movetime 0 %u\n", (unsigned int)&ob->plg_movetime ); // atomic
	printf("Ob u32 plg_counterstart 0 %u\n", (unsigned int)&ob->plg_counterstart ); // atomic
	printf("Ob u32 plg_moveto_done 0 %u\n", (unsigned int)&ob->plg_moveto_done ); // atomic
	printf("Ob f64 plg_last_fX 0 %u\n", (unsigned int)&ob->plg_last_fX ); // atomic
	printf("Ob f64 plg_last_fY 0 %u\n", (unsigned int)&ob->plg_last_fY ); // atomic
	printf("Ob f64 plg_channel_width 0 %u\n", (unsigned int)&ob->plg_channel_width ); // atomic
	printf("Ob u32 ba_accumforce 0 %u\n", (unsigned int)&ob->ba_accumforce ); // atomic
	printf("Ob f64 mkt_mvtangle 0 %u\n", (unsigned int)&ob->mkt_mvtangle ); // atomic
	printf("Ob f64 mkt_finline 0 %u\n", (unsigned int)&ob->mkt_finline ); // atomic
	printf("Ob f64 mkt_fortho 0 %u\n", (unsigned int)&ob->mkt_fortho ); // atomic
	printf("Ob f64 ba_fx 0 %u\n", (unsigned int)&ob->ba_fx ); // atomic
	printf("Ob f64 ba_fy 0 %u\n", (unsigned int)&ob->ba_fy ); // atomic
	printf("Ob f64 ba_position 0 %u\n", (unsigned int)&ob->ba_position ); // atomic
	printf("Ob u32 mkt_isMcGill 0 %u\n", (unsigned int)&ob->mkt_isMcGill ); // atomic
	printf("Ob u32 fvv_trial_phase 0 %u\n", (unsigned int)&ob->fvv_trial_phase ); // atomic
	printf("Ob u32 fvv_trial_no 0 %u\n", (unsigned int)&ob->fvv_trial_no ); // atomic
	printf("Ob u32 fvv_move_done 0 %u\n", (unsigned int)&ob->fvv_move_done ); // atomic
	printf("Ob f64 fvv_robot_center_x 0 %u\n", (unsigned int)&ob->fvv_robot_center_x ); // atomic
	printf("Ob f64 fvv_robot_center_y 0 %u\n", (unsigned int)&ob->fvv_robot_center_y ); // atomic
	printf("Ob f64 fvv_force_fade 0 %u\n", (unsigned int)&ob->fvv_force_fade ); // atomic
	printf("Ob f64 fvv_robot_min_y 0 %u\n", (unsigned int)&ob->fvv_robot_min_y ); // atomic
	printf("Ob f64 fvv_min_dist 0 %u\n", (unsigned int)&ob->fvv_min_dist ); // atomic
	printf("Ob f64 fvv_vel 0 %u\n", (unsigned int)&ob->fvv_vel ); // atomic
	printf("Ob f64 fvv_max_vel 0 %u\n", (unsigned int)&ob->fvv_max_vel ); // atomic
	printf("Ob f64 fvv_vmax_x 0 %u\n", (unsigned int)&ob->fvv_vmax_x ); // atomic
	printf("Ob f64 fvv_vmax_y 0 %u\n", (unsigned int)&ob->fvv_vmax_y ); // atomic
	printf("Ob f64 fvv_final_x 0 %u\n", (unsigned int)&ob->fvv_final_x ); // atomic
	printf("Ob f64 fvv_final_y 0 %u\n", (unsigned int)&ob->fvv_final_y ); // atomic
	printf("Ob u32 fvv_trial_timer 0 %u\n", (unsigned int)&ob->fvv_trial_timer ); // atomic
	printf("Ob u32 fvv_vel_low_timer 0 %u\n", (unsigned int)&ob->fvv_vel_low_timer ); // atomic
	printf("Ob u32 fvv_subject_move_phase 0 %u\n", (unsigned int)&ob->fvv_subject_move_phase ); // atomic
	printf("Ob u32 fvv_capture 0 %u\n", (unsigned int)&ob->fvv_capture ); // atomic
	printf("Ob u32 fvv_workspace_enter 0 %u\n", (unsigned int)&ob->fvv_workspace_enter ); // atomic
	printf("Ob f64 fvv_curl_force_x 0 %u\n", (unsigned int)&ob->fvv_curl_force.x ); // atomic
	printf("Ob f64 fvv_curl_force_y 0 %u\n", (unsigned int)&ob->fvv_curl_force.y ); // atomic
	printf("Ob u32 traj_n_samps 0 %u\n", (unsigned int)&ob->traj_n_samps ); // atomic
	printf("Ob u32 traj_count 0 %u\n", (unsigned int)&ob->traj_count ); // atomic
	printf("Ob f64 trajx 3000 %u\n", (unsigned int)&ob->trajx ); // atomic
	printf("Ob f64 trajy 3000 %u\n", (unsigned int)&ob->trajy ); // atomic
	printf("Ob f64 recordfx 3000 %u\n", (unsigned int)&ob->recordfx ); // atomic
	printf("Ob f64 recordfy 3000 %u\n", (unsigned int)&ob->recordfy ); // atomic
	printf("Ob f64 recordfz 3000 %u\n", (unsigned int)&ob->recordfz ); // atomic
	printf("Ob f64 traj_final_x 0 %u\n", (unsigned int)&ob->traj_final_x ); // atomic
	printf("Ob f64 traj_final_y 0 %u\n", (unsigned int)&ob->traj_final_y ); // atomic
	printf("Ob u32 replay_done 0 %u\n", (unsigned int)&ob->replay_done ); // atomic
	printf("Ob f64 replay_damping 0 %u\n", (unsigned int)&ob->replay_damping ); // atomic
	printf("Ob f64 replay_stiffness 0 %u\n", (unsigned int)&ob->replay_stiffness ); // atomic
	printf("Ob s32 debug_level 0 %u\n", (unsigned int)&ob->debug_level ); // atomic
	printf("Ob u32 last_shm_val 0 %u\n", (unsigned int)&ob->last_shm_val ); // atomic
	printf("Robot s8 tag 8 %u\n", (unsigned int)&robot->tag ); // atomic
	printf("Robot f64 ain_07 0 %u\n", (unsigned int)&robot->ain_07 ); // atomic
	printf("Robot u32 ain_07_channel 0 %u\n", (unsigned int)&robot->ain_07_channel ); // atomic
	printf("Robot u32 shoulder_angle_channel 0 %u\n", (unsigned int)&robot->shoulder.angle.channel ); // atomic
	printf("Robot f64 shoulder_angle_xform 0 %u\n", (unsigned int)&robot->shoulder.angle.xform ); // atomic
	printf("Robot f64 shoulder_angle_offset 0 %u\n", (unsigned int)&robot->shoulder.angle.offset ); // atomic
	printf("Robot f64 shoulder_angle_raw 0 %u\n", (unsigned int)&robot->shoulder.angle.raw ); // atomic
	printf("Robot f64 shoulder_angle_rad 0 %u\n", (unsigned int)&robot->shoulder.angle.rad ); // atomic
	printf("Robot f64 shoulder_angle_deg 0 %u\n", (unsigned int)&robot->shoulder.angle.deg ); // atomic
	printf("Robot f64 shoulder_angle_cal 0 %u\n", (unsigned int)&robot->shoulder.angle.cal ); // atomic
	printf("Robot u32 shoulder_vel_channel 0 %u\n", (unsigned int)&robot->shoulder.vel.channel ); // atomic
	printf("Robot f64 shoulder_vel_xform 0 %u\n", (unsigned int)&robot->shoulder.vel.xform ); // atomic
	printf("Robot f64 shoulder_vel_offset 0 %u\n", (unsigned int)&robot->shoulder.vel.offset ); // atomic
	printf("Robot f64 shoulder_vel_raw 0 %u\n", (unsigned int)&robot->shoulder.vel.raw ); // atomic
	printf("Robot f64 shoulder_vel_rad 0 %u\n", (unsigned int)&robot->shoulder.vel.rad ); // atomic
	printf("Robot f64 shoulder_vel_deg 0 %u\n", (unsigned int)&robot->shoulder.vel.deg ); // atomic
	printf("Robot f64 shoulder_vel_cal 0 %u\n", (unsigned int)&robot->shoulder.vel.cal ); // atomic
	printf("Robot u32 shoulder_torque_channel 0 %u\n", (unsigned int)&robot->shoulder.torque.channel ); // atomic
	printf("Robot f64 shoulder_torque_xform 0 %u\n", (unsigned int)&robot->shoulder.torque.xform ); // atomic
	printf("Robot f64 shoulder_torque_offset 0 %u\n", (unsigned int)&robot->shoulder.torque.offset ); // atomic
	printf("Robot f64 shoulder_torque_raw 0 %u\n", (unsigned int)&robot->shoulder.torque.raw ); // atomic
	printf("Robot f64 shoulder_torque_rad 0 %u\n", (unsigned int)&robot->shoulder.torque.rad ); // atomic
	printf("Robot f64 shoulder_torque_deg 0 %u\n", (unsigned int)&robot->shoulder.torque.deg ); // atomic
	printf("Robot f64 shoulder_torque_cal 0 %u\n", (unsigned int)&robot->shoulder.torque.cal ); // atomic
	printf("Robot u32 elbow_angle_channel 0 %u\n", (unsigned int)&robot->elbow.angle.channel ); // atomic
	printf("Robot f64 elbow_angle_xform 0 %u\n", (unsigned int)&robot->elbow.angle.xform ); // atomic
	printf("Robot f64 elbow_angle_offset 0 %u\n", (unsigned int)&robot->elbow.angle.offset ); // atomic
	printf("Robot f64 elbow_angle_raw 0 %u\n", (unsigned int)&robot->elbow.angle.raw ); // atomic
	printf("Robot f64 elbow_angle_rad 0 %u\n", (unsigned int)&robot->elbow.angle.rad ); // atomic
	printf("Robot f64 elbow_angle_deg 0 %u\n", (unsigned int)&robot->elbow.angle.deg ); // atomic
	printf("Robot f64 elbow_angle_cal 0 %u\n", (unsigned int)&robot->elbow.angle.cal ); // atomic
	printf("Robot u32 elbow_vel_channel 0 %u\n", (unsigned int)&robot->elbow.vel.channel ); // atomic
	printf("Robot f64 elbow_vel_xform 0 %u\n", (unsigned int)&robot->elbow.vel.xform ); // atomic
	printf("Robot f64 elbow_vel_offset 0 %u\n", (unsigned int)&robot->elbow.vel.offset ); // atomic
	printf("Robot f64 elbow_vel_raw 0 %u\n", (unsigned int)&robot->elbow.vel.raw ); // atomic
	printf("Robot f64 elbow_vel_rad 0 %u\n", (unsigned int)&robot->elbow.vel.rad ); // atomic
	printf("Robot f64 elbow_vel_deg 0 %u\n", (unsigned int)&robot->elbow.vel.deg ); // atomic
	printf("Robot f64 elbow_vel_cal 0 %u\n", (unsigned int)&robot->elbow.vel.cal ); // atomic
	printf("Robot u32 elbow_torque_channel 0 %u\n", (unsigned int)&robot->elbow.torque.channel ); // atomic
	printf("Robot f64 elbow_torque_xform 0 %u\n", (unsigned int)&robot->elbow.torque.xform ); // atomic
	printf("Robot f64 elbow_torque_offset 0 %u\n", (unsigned int)&robot->elbow.torque.offset ); // atomic
	printf("Robot f64 elbow_torque_raw 0 %u\n", (unsigned int)&robot->elbow.torque.raw ); // atomic
	printf("Robot f64 elbow_torque_rad 0 %u\n", (unsigned int)&robot->elbow.torque.rad ); // atomic
	printf("Robot f64 elbow_torque_deg 0 %u\n", (unsigned int)&robot->elbow.torque.deg ); // atomic
	printf("Robot f64 elbow_torque_cal 0 %u\n", (unsigned int)&robot->elbow.torque.cal ); // atomic
	printf("Robot f64 link_s 0 %u\n", (unsigned int)&robot->link.s ); // atomic
	printf("Robot f64 link_e 0 %u\n", (unsigned int)&robot->link.e ); // atomic
	printf("Robot f64 offset_x 0 %u\n", (unsigned int)&robot->offset.x ); // atomic
	printf("Robot f64 offset_y 0 %u\n", (unsigned int)&robot->offset.y ); // atomic
	printf("Robot u32 ft_flip 0 %u\n", (unsigned int)&robot->ft.flip ); // atomic
	printf("Robot u32 ft_vert 0 %u\n", (unsigned int)&robot->ft.vert ); // atomic
	printf("Robot u32 ft_channel 6 %u\n", (unsigned int)&robot->ft.channel ); // atomic
	printf("Robot f64 ft_offset 0 %u\n", (unsigned int)&robot->ft.offset ); // atomic
	printf("Robot f64 ft_curr 6 %u\n", (unsigned int)&robot->ft.curr ); // atomic
	printf("Robot f64 ft_prev 6 %u\n", (unsigned int)&robot->ft.prev ); // atomic
	printf("Robot f64 ft_filt 6 %u\n", (unsigned int)&robot->ft.filt ); // atomic
	printf("Robot f64 ft_prevf 6 %u\n", (unsigned int)&robot->ft.prevf ); // atomic
	printf("Robot f64 ft_world_x 0 %u\n", (unsigned int)&robot->ft.world.x ); // atomic
	printf("Robot f64 ft_world_y 0 %u\n", (unsigned int)&robot->ft.world.y ); // atomic
	printf("Robot f64 ft_world_z 0 %u\n", (unsigned int)&robot->ft.world.z ); // atomic
	printf("Robot f64 ft_dev_x 0 %u\n", (unsigned int)&robot->ft.dev.x ); // atomic
	printf("Robot f64 ft_dev_y 0 %u\n", (unsigned int)&robot->ft.dev.y ); // atomic
	printf("Robot f64 ft_dev_z 0 %u\n", (unsigned int)&robot->ft.dev.z ); // atomic
	printf("Robot f64 ft_moment_x 0 %u\n", (unsigned int)&robot->ft.moment.x ); // atomic
	printf("Robot f64 ft_moment_y 0 %u\n", (unsigned int)&robot->ft.moment.y ); // atomic
	printf("Robot f64 ft_moment_z 0 %u\n", (unsigned int)&robot->ft.moment.z ); // atomic
	printf("Robot f64 ft_xymag 0 %u\n", (unsigned int)&robot->ft.xymag ); // atomic
	printf("Robot u32 ft_dobias 0 %u\n", (unsigned int)&robot->ft.dobias ); // atomic
	printf("Robot f64 ft_raw 6 %u\n", (unsigned int)&robot->ft.raw ); // atomic
	printf("Robot f64 ft_cooked 6 %u\n", (unsigned int)&robot->ft.cooked ); // atomic
	printf("Robot f64 ft_bias 6 %u\n", (unsigned int)&robot->ft.bias ); // atomic
	printf("Robot f64 ft_scale 6 %u\n", (unsigned int)&robot->ft.scale ); // atomic
	printf("Robot f64 ft_cal 36 %u\n", (unsigned int)&robot->ft.cal ); // atomic
	printf("Robot f64 ft_avg 6 %u\n", (unsigned int)&robot->ft.avg ); // atomic
	printf("Robot f64 ft_but 6 %u\n", (unsigned int)&robot->ft.but ); // atomic
	printf("Robot f64 ft_sg 6 %u\n", (unsigned int)&robot->ft.sg ); // atomic
	printf("Robot f64 ft_sghist 384 %u\n", (unsigned int)&robot->ft.sghist ); // atomic
	printf("Robot f64 ft_bsrawhist 96 %u\n", (unsigned int)&robot->ft.bsrawhist ); // atomic
	printf("Robot f64 ft_bsfilthist 96 %u\n", (unsigned int)&robot->ft.bsfilthist ); // atomic
	printf("Robot f64 ft_bs 6 %u\n", (unsigned int)&robot->ft.bs ); // atomic
	printf("Robot u16 isaft_cpf 0 %u\n", (unsigned int)&robot->isaft.cpf ); // atomic
	printf("Robot u16 isaft_cpt 0 %u\n", (unsigned int)&robot->isaft.cpt ); // atomic
	printf("Robot u16 isaft_units 0 %u\n", (unsigned int)&robot->isaft.units ); // atomic
	printf("Robot s32 isaft_iraw 8 %u\n", (unsigned int)&robot->isaft.iraw ); // atomic
	printf("Robot f64 isaft_raw 8 %u\n", (unsigned int)&robot->isaft.raw ); // atomic
	printf("Robot u32 grasp_channel 0 %u\n", (unsigned int)&robot->grasp.channel ); // atomic
	printf("Robot f64 grasp_raw 0 %u\n", (unsigned int)&robot->grasp.raw ); // atomic
	printf("Robot f64 grasp_bias 0 %u\n", (unsigned int)&robot->grasp.bias ); // atomic
	printf("Robot f64 grasp_cal 0 %u\n", (unsigned int)&robot->grasp.cal ); // atomic
	printf("Robot f64 grasp_gain 0 %u\n", (unsigned int)&robot->grasp.gain ); // atomic
	printf("Robot f64 grasp_force 0 %u\n", (unsigned int)&robot->grasp.force ); // atomic
	printf("Robot f64 grasp_press 0 %u\n", (unsigned int)&robot->grasp.press ); // atomic
	printf("Robot f64 grasp_release 0 %u\n", (unsigned int)&robot->grasp.release ); // atomic
	printf("Robot u32 accel_channel 3 %u\n", (unsigned int)&robot->accel.channel ); // atomic
	printf("Robot f64 accel_raw 3 %u\n", (unsigned int)&robot->accel.raw ); // atomic
	printf("Robot f64 accel_curr 3 %u\n", (unsigned int)&robot->accel.curr ); // atomic
	printf("Robot f64 accel_prev 3 %u\n", (unsigned int)&robot->accel.prev ); // atomic
	printf("Robot f64 accel_filt 3 %u\n", (unsigned int)&robot->accel.filt ); // atomic
	printf("Robot f64 accel_prevf 3 %u\n", (unsigned int)&robot->accel.prevf ); // atomic
	printf("Robot f64 accel_world_x 0 %u\n", (unsigned int)&robot->accel.world.x ); // atomic
	printf("Robot f64 accel_world_y 0 %u\n", (unsigned int)&robot->accel.world.y ); // atomic
	printf("Robot f64 accel_world_z 0 %u\n", (unsigned int)&robot->accel.world.z ); // atomic
	printf("Robot f64 accel_dev_x 0 %u\n", (unsigned int)&robot->accel.dev.x ); // atomic
	printf("Robot f64 accel_dev_y 0 %u\n", (unsigned int)&robot->accel.dev.y ); // atomic
	printf("Robot f64 accel_dev_z 0 %u\n", (unsigned int)&robot->accel.dev.z ); // atomic
	printf("Robot f64 accel_bias 3 %u\n", (unsigned int)&robot->accel.bias ); // atomic
	printf("Robot f64 accel_xform 0 %u\n", (unsigned int)&robot->accel.xform ); // atomic
	printf("Robot u32 csen_have 0 %u\n", (unsigned int)&robot->csen.have ); // atomic
	printf("Robot u32 csen_channela 8 %u\n", (unsigned int)&robot->csen.channela ); // atomic
	printf("Robot u32 csen_channelc 8 %u\n", (unsigned int)&robot->csen.channelc ); // atomic
	printf("Robot f64 csen_rawa 8 %u\n", (unsigned int)&robot->csen.rawa ); // atomic
	printf("Robot f64 csen_rawc 8 %u\n", (unsigned int)&robot->csen.rawc ); // atomic
	printf("Robot f64 csen_xforma 8 %u\n", (unsigned int)&robot->csen.xforma ); // atomic
	printf("Robot f64 csen_xformc 8 %u\n", (unsigned int)&robot->csen.xformc ); // atomic
	printf("Robot f64 csen_kt 8 %u\n", (unsigned int)&robot->csen.kt ); // atomic
	printf("Robot f64 csen_kt_biasa 8 %u\n", (unsigned int)&robot->csen.kt_biasa ); // atomic
	printf("Robot f64 csen_kt_biasc 8 %u\n", (unsigned int)&robot->csen.kt_biasc ); // atomic
	printf("Robot f64 csen_alpha 8 %u\n", (unsigned int)&robot->csen.alpha ); // atomic
	printf("Robot f64 csen_curr 8 %u\n", (unsigned int)&robot->csen.curr ); // atomic
	printf("Robot f64 csen_torque 8 %u\n", (unsigned int)&robot->csen.torque ); // atomic
	printf("Robot u32 linear_motor_enc_channel 0 %u\n", (unsigned int)&robot->linear.motor.enc_channel ); // atomic
	printf("Robot f64 linear_motor_disp 0 %u\n", (unsigned int)&robot->linear.motor.disp ); // atomic
	printf("Robot f64 linear_motor_devfrc 0 %u\n", (unsigned int)&robot->linear.motor.devfrc ); // atomic
	printf("Robot f64 linear_motor_xform 0 %u\n", (unsigned int)&robot->linear.motor.xform ); // atomic
	printf("Robot f64 linear_motor_volts 0 %u\n", (unsigned int)&robot->linear.motor.volts ); // atomic
	printf("Robot f64 linear_motor_test_volts 0 %u\n", (unsigned int)&robot->linear.motor.test_volts ); // atomic
	printf("Robot u32 linear_motor_ao_channel 0 %u\n", (unsigned int)&robot->linear.motor.ao_channel ); // atomic
	printf("Robot u32 linear_motor_limit_channel 0 %u\n", (unsigned int)&robot->linear.motor.limit_channel ); // atomic
	printf("Robot f64 linear_motor_limit_volts 0 %u\n", (unsigned int)&robot->linear.motor.limit_volts ); // atomic
	printf("Robot f64 linear_gears_ratio 0 %u\n", (unsigned int)&robot->linear.gears.ratio ); // atomic
	printf("Robot u32 linear_uei_ao_board_handle 0 %u\n", (unsigned int)&robot->linear.uei_ao_board_handle ); // atomic
	printf("Daq s8 tag 8 %u\n", (unsigned int)&daq->tag ); // atomic
	printf("Daq s32 n_ueidaq_boards 0 %u\n", (unsigned int)&daq->n_ueidaq_boards ); // atomic
	printf("Daq s32 uei_board 4 %u\n", (unsigned int)&daq->uei_board ); // atomic
	printf("Daq s32 ain_handle 4 %u\n", (unsigned int)&daq->ain_handle ); // atomic
	printf("Daq s32 aout_handle 4 %u\n", (unsigned int)&daq->aout_handle ); // atomic
	printf("Daq s32 din_handle 4 %u\n", (unsigned int)&daq->din_handle ); // atomic
	printf("Daq s32 dout_handle 4 %u\n", (unsigned int)&daq->dout_handle ); // atomic
	printf("Daq s32 ao8_handle 4 %u\n", (unsigned int)&daq->ao8_handle ); // atomic
	printf("Daq u32 adapter_type 4 %u\n", (unsigned int)&daq->adapter_type ); // atomic
	printf("Daq s32 ain_cl_size 0 %u\n", (unsigned int)&daq->ain_cl_size ); // atomic
	printf("Daq s32 ain_ret 0 %u\n", (unsigned int)&daq->ain_ret ); // atomic
	printf("Daq u32 ain_got_samples 0 %u\n", (unsigned int)&daq->ain_got_samples ); // atomic
	printf("Daq u32 ain_cfg 0 %u\n", (unsigned int)&daq->ain_cfg ); // atomic
	printf("Daq f64 ain_bias_comp 4 %u\n", (unsigned int)&daq->ain_bias_comp ); // atomic
	printf("Daq u16 m_dienc 8 %u\n", (unsigned int)&daq->m_dienc ); // atomic
	printf("Daq u16 m_dout_buf 4 %u\n", (unsigned int)&daq->m_dout_buf ); // atomic
	printf("Daq u16 m_adc 64 %u\n", (unsigned int)&daq->m_adc ); // atomic
	printf("Daq u16 m_dac 64 %u\n", (unsigned int)&daq->m_dac ); // atomic
	printf("Daq f64 m_adcvoltsmean 64 %u\n", (unsigned int)&daq->m_adcvoltsmean ); // atomic
	printf("Daq f64 m_adcvoltsmed 64 %u\n", (unsigned int)&daq->m_adcvoltsmed ); // atomic
	printf("Daq f64 m_adcvoltsprev 64 %u\n", (unsigned int)&daq->m_adcvoltsprev ); // atomic
	printf("Daq f64 m_adcvoltsfilt 64 %u\n", (unsigned int)&daq->m_adcvoltsfilt ); // atomic
	printf("Daq f64 m_adcvoltspfilt 64 %u\n", (unsigned int)&daq->m_adcvoltspfilt ); // atomic
	printf("Daq f64 m_adcvolts 64 %u\n", (unsigned int)&daq->m_adcvolts ); // atomic
	printf("Daq f64 m_dacvolts 64 %u\n", (unsigned int)&daq->m_dacvolts ); // atomic
	printf("Daq u16 dout0 0 %u\n", (unsigned int)&daq->dout0 ); // atomic
	printf("Daq u16 dout1 0 %u\n", (unsigned int)&daq->dout1 ); // atomic
	printf("Daq u16 distat 2 %u\n", (unsigned int)&daq->distat ); // atomic
	printf("Daq u16 prev_dienc 2 %u\n", (unsigned int)&daq->prev_dienc ); // atomic
	printf("Daq s32 dienc_vel 2 %u\n", (unsigned int)&daq->dienc_vel ); // atomic
	printf("Daq s32 prev_dienc_vel 2 %u\n", (unsigned int)&daq->prev_dienc_vel ); // atomic
	printf("Daq s32 dienc_accel 2 %u\n", (unsigned int)&daq->dienc_accel ); // atomic
	printf("Daq u32 diovs 0 %u\n", (unsigned int)&daq->diovs ); // atomic
	printf("Game u32 go 0 %u\n", (unsigned int)&game->go ); // atomic
	printf("Game f64 planet_color_red 9 %u\n", (unsigned int)&game->planet_color_red ); // atomic
	printf("Game f64 planet_color_green 9 %u\n", (unsigned int)&game->planet_color_green ); // atomic
	printf("Game f64 planet_color_blue 9 %u\n", (unsigned int)&game->planet_color_blue ); // atomic
	printf("Game u32 planet_color_go 9 %u\n", (unsigned int)&game->planet_color_go ); // atomic
	printf("Game f64 planet_default_red 0 %u\n", (unsigned int)&game->planet_default_red ); // atomic
	printf("Game f64 planet_default_green 0 %u\n", (unsigned int)&game->planet_default_green ); // atomic
	printf("Game f64 planet_default_blue 0 %u\n", (unsigned int)&game->planet_default_blue ); // atomic
	printf("Game f64 planet_rotation_aa 9 %u\n", (unsigned int)&game->planet_rotation_aa ); // atomic
	printf("Game f64 planet_rotation_ps 9 %u\n", (unsigned int)&game->planet_rotation_ps ); // atomic
	printf("Game f64 planet_rotation_fe 9 %u\n", (unsigned int)&game->planet_rotation_fe ); // atomic
	printf("Game u32 planet_rotation_go 9 %u\n", (unsigned int)&game->planet_rotation_go ); // atomic
	printf("Game u32 repetition 0 %u\n", (unsigned int)&game->repetition ); // atomic
	printf("Game u32 total_repetitions 0 %u\n", (unsigned int)&game->total_repetitions ); // atomic
	printf("Game u32 repetition_go 0 %u\n", (unsigned int)&game->repetition_go ); // atomic
	printf("Game u32 key_spacebar 0 %u\n", (unsigned int)&game->key_spacebar ); // atomic
	printf("Game u32 key_quit 0 %u\n", (unsigned int)&game->key_quit ); // atomic
	printf("Game u32 key_b 0 %u\n", (unsigned int)&game->key_b ); // atomic
	printf("Game u32 target 0 %u\n", (unsigned int)&game->target ); // atomic
	printf("Game u32 target_go 0 %u\n", (unsigned int)&game->target_go ); // atomic
	printf("Game u32 target_hit 0 %u\n", (unsigned int)&game->target_hit ); // atomic
	printf("Game f64 feSlack 0 %u\n", (unsigned int)&game->feSlack ); // atomic
	printf("Game f64 psSlack 0 %u\n", (unsigned int)&game->psSlack ); // atomic
	printf("Game f64 aaSlack 0 %u\n", (unsigned int)&game->aaSlack ); // atomic
	printf("Game f64 planarSlack 0 %u\n", (unsigned int)&game->planarSlack ); // atomic
	printf("Game u32 slack_go 0 %u\n", (unsigned int)&game->slack_go ); // atomic
	printf("Game u32 active_target 0 %u\n", (unsigned int)&game->active_target ); // atomic
	printf("Game u32 active_target_go 0 %u\n", (unsigned int)&game->active_target_go ); // atomic
	printf("Game u32 quit_server 0 %u\n", (unsigned int)&game->quit_server ); // atomic
	printf("Moh f64 pointer 0 %u\n", (unsigned int)&moh->pointer ); // atomic
	printf("Moh u32 pixelx 36 %u\n", (unsigned int)&moh->pixelx ); // atomic
	printf("Moh u32 pixely 36 %u\n", (unsigned int)&moh->pixely ); // atomic
	printf("Moh f64 realx 36 %u\n", (unsigned int)&moh->realx ); // atomic
	printf("Moh f64 realy 36 %u\n", (unsigned int)&moh->realy ); // atomic
	printf("Moh f64 xcenter 0 %u\n", (unsigned int)&moh->xcenter ); // atomic
	printf("Moh f64 ycenter 0 %u\n", (unsigned int)&moh->ycenter ); // atomic
	printf("Moh f64 ffs 0 %u\n", (unsigned int)&moh->ffs ); // atomic
	printf("Moh f64 hand_place 0 %u\n", (unsigned int)&moh->hand_place ); // atomic
	printf("Moh f64 stiffness 0 %u\n", (unsigned int)&moh->stiffness ); // atomic
	printf("Moh f64 move_flag 0 %u\n", (unsigned int)&moh->move_flag ); // atomic
	printf("Moh f64 servo_flag 0 %u\n", (unsigned int)&moh->servo_flag ); // atomic
	printf("Moh f64 counter 0 %u\n", (unsigned int)&moh->counter ); // atomic
	printf("Moh f64 current_dir 0 %u\n", (unsigned int)&moh->current_dir ); // atomic
	printf("Moh f64 last_pointX 0 %u\n", (unsigned int)&moh->last_pointX ); // atomic
	printf("Moh f64 last_pointY 0 %u\n", (unsigned int)&moh->last_pointY ); // atomic
	printf("Moh f64 fX 0 %u\n", (unsigned int)&moh->fX ); // atomic
	printf("Moh f64 fY 0 %u\n", (unsigned int)&moh->fY ); // atomic
	printf("Dyncmp_var u32 usedirectcontrol 0 %u\n", (unsigned int)&dyncmp_var->usedirectcontrol ); // atomic
	printf("Dyncmp_var f64 control_force_x 0 %u\n", (unsigned int)&dyncmp_var->control_force.x ); // atomic
	printf("Dyncmp_var f64 control_force_y 0 %u\n", (unsigned int)&dyncmp_var->control_force.y ); // atomic
	printf("Dyncmp_var f64 anglevelocity_s 0 %u\n", (unsigned int)&dyncmp_var->anglevelocity.s ); // atomic
	printf("Dyncmp_var f64 anglevelocity_e 0 %u\n", (unsigned int)&dyncmp_var->anglevelocity.e ); // atomic
	printf("Dyncmp_var f64 Corriolis_s 0 %u\n", (unsigned int)&dyncmp_var->Corriolis.s ); // atomic
	printf("Dyncmp_var f64 Corriolis_e 0 %u\n", (unsigned int)&dyncmp_var->Corriolis.e ); // atomic
	printf("Dyncmp_var f64 Bofq_e00 0 %u\n", (unsigned int)&dyncmp_var->Bofq.e00 ); // atomic
	printf("Dyncmp_var f64 Bofq_e01 0 %u\n", (unsigned int)&dyncmp_var->Bofq.e01 ); // atomic
	printf("Dyncmp_var f64 Bofq_e10 0 %u\n", (unsigned int)&dyncmp_var->Bofq.e10 ); // atomic
	printf("Dyncmp_var f64 Bofq_e11 0 %u\n", (unsigned int)&dyncmp_var->Bofq.e11 ); // atomic
	printf("Dyncmp_var f64 Mofq_e00 0 %u\n", (unsigned int)&dyncmp_var->Mofq.e00 ); // atomic
	printf("Dyncmp_var f64 Mofq_e01 0 %u\n", (unsigned int)&dyncmp_var->Mofq.e01 ); // atomic
	printf("Dyncmp_var f64 Mofq_e10 0 %u\n", (unsigned int)&dyncmp_var->Mofq.e10 ); // atomic
	printf("Dyncmp_var f64 Mofq_e11 0 %u\n", (unsigned int)&dyncmp_var->Mofq.e11 ); // atomic
	return 0;
}


